import { AdminrhDemandeComponent } from "../../../features/adminrh/adminrh-demande/adminrh-demande.component";
import { AdminrhStatementsComponent } from "../../../features/adminrh/adminrh-statements/adminrh-statements.component";

export const routes = {
  // Instructor Routes
  instructor: '/instructor/',
  instructor_dashboard: '/instructor/instructor-dashboard',
  instructor_payouts: '/instructor/instructor-payouts',
  instructor_tickets: '/instructor/instructor-tickets',
  instructorAnnouncements: '/instructor/instructor-announcements',
  instructorAssignment: '/instructor/instructor-assignment',
  instructorWishlist: '/instructor/instructor-wishlist',
  instructorWithdraw: '/instructor/instructor-withdraw',
  instructorProfile: '/instructor/instructor-profile',
  instructorQuizQuestions: '/instructor/instructor-quiz-questions',
  instructorQuiz: '/instructor/instructor-quiz',
  instructorCertificate: '/instructor/instructor-certificate',
  instructorEarning: '/instructor/instructor-earnings',
  instructorStatements: '/instructor/instructor-statements',
  quiz: 'quiz',
  studentsList: '/instructor/students-list',
  studentsGrid: '/instructor/students-grid',
  studentsDetails: '/instructor/students-details',
  instructorQuizResult: '/instructor/instructor-quiz-results',
  instructorCourse: '/instructor/instructor-course',
  instructorCourseGrid: '/instructor/instructor-course-grid',
  instructorSession: '/instructor/instructor-session',
  instructorMesSondages: '/instructor/instructor-mes-sondages',
  instructorVideoRessources: '/instructor/video-ressources',
  instructorTickets: '/instructor/instructor-tickets',
  instructorMessage: '/instructor/instructor-message',
  instructorQuizDetails: '/instructor/instructor-quiz-details',
  instructorSettingWithdraw: '/instructor/settings/instructor-setting-withdraw',
  instructorSettingNotifications: '/instructor/settings/instructor-setting-notifications',
  instructorPlans: '/instructor/settings/instructor-plans',
  instructorIntegrations: '/instructor/settings/instructor-integrations',
  instructorLinkedAccounts: '/instructor/settings/instructor-linked-accounts',
  instructorSocialProfiles: '/instructor/settings/instructor-social-profiles',
  instructorDeleteAccount: '/instructor/settings/instructor-delete-account',
  instructorChangePassword: '/instructor/settings/instructor-change-password',
  instructorSettings: '/instructor/settings/instructor-settings',
  instructorGuideUtilisation: '/instructor/guide-utilisation',
  instructorTutorielsVideo: '/instructor/tutoriels-video',
  instructorAnnoncesMAJ: '/instructor/instructor-announcements',

  // Student Routes
  students: '/student/',
  students_profile: '/student/student-profile',
  students_Dashboard: '/student/student-dashboard',
  student_DemandeFormation: '/student/student-demande',
  course_student: '/student/course-student',
  studentMyCourses: '/student/mes-formations',           // ✅ mes-cours → mes-formations
  student_Certificate: '/student/student-certificate',
  studentDemande: '/student/student-demande',
  student_Wishlist: '/student/student-wishlist',
  view_invoice_student: '/student/view-invoice',
  transactions_student: '/student/transactions-student',
  students_security: '/student/setting-student-security',
  students_notification: '/student/setting-student-notification',
  students_privacy: '/student/setting-student-privacy',
  students_delete: '/student/setting-student-delete-profile',
  students_accounts: '/student/setting-student-accounts',
  students_referral: '/student/student-referral',
  students_subscription: '/student/setting-student-subscription',
  students_billing: '/student/setting-student-billing',
  students_payments: '/student/setting-student-payment',
  students_invoice: '/student/setting-student-invoice',
  students_tickets: '/student/student-tickets',
  students_message: '/student/student-message',
  // ✅ CORRIGÉ : pointe vers la route top-level /student/quiz/:id (usage: navigate([routes.students_quiz_question, id]))
  students_quiz_question: '/student/quiz',
  students_quiz: '/student/student-quiz',
  studentsQuizQuestion: '/student/quiz',               // ✅ CORRIGÉ (alias)
  studentsQuiz: '/student/student-quiz',
  studentMesSondages: '/student/student-mes-sondages',
  studentSondage: '/student/student-sondage',
  studentProfile: '/student/student-profile',
  student_MesCompetences: '/student/mes-competences',
  student_CompetencesRecommandees: '/student/mes-competences-recommandees',
  student_EcartCompetences: '/student/ecart-competences',
  student_Planning: '/student/student-planning',
  studentGuideUtilisation: '/student/guide-utilisation',
  studentTutorielsVideo: '/student/tutoriels-video',
  studentAnnoncesMAJ: '/student/annonces-maj',
  student_MesPalmares: '/student/mes-palmares',
  studentMessages: '/student/student-message',
  studentsMessage: '/student/student-message',
  studentOrderHistory: '/student/student-order-history',
  studentWishlist: '/student/student-wishlist',
  studentCourses: '/student/mes-catalogues',             // ✅ student-courses → mes-catalogues
  studentReviews: '/student/student-reviews',
  studentQuizDetails: '/student/student-quiz-details',
  studentQuiz: '/student/student-quiz',
  studentLinkedAccount: '/student/settings/student-linked-accounts',
  studentNotification: '/student/settings/student-notifications',
  students_social_profile: '/student/settings/student-social-profile',
  studentChangePassword: '/student/settings/student-change-password',
  studentSettings: '/student/settings/student-settings',
  studentBillingAddress: '/student/settings/student-billing-address',
  studentExplorer : '/student/students-explorer' ,
  // Demandes — alignées sur app.routes.ts
  student_DemandeSession:   '/student/students-session',
  student_DemandeCatalogue: '/student/student-demande-catalogue',
  student_DemandeParcours:  '/student/mes-demandes-parcours',
  studentCertificat: '/student/student-certificate',


  // Mes parcours et catalogues assignés
  student_CataloguesAssignes: '/student/mes-catalogues',
  student_ParcoursAssignes:   '/student/mes-parcours',
  student_SessionsAcceptees:  '/student/sessions-acceptees',

  // SuperAdmin Routes
  superadmin: '/superadmin/',
  superadmin_dashboard: '/superadmin/superadmin-dashboard',
  superadmin_payouts: '/superadmin/superadmin-payouts',
  superadmin_tickets: '/superadmin/superadmin-tickets',
  superadminAnnouncements: '/superadmin/superadmin-announcements',
  superadminAssignment: '/superadmin/superadmin-assignment',
  superadminWishliast: '/superadmin/superadmin-wishlist',
  superadminWithdraw: '/superadmin/superadmin-withdraw',
  superadminProfile: '/superadmin/superadmin-profile',
  superadminQuizQuestion: '/superadmin/superadmin-quiz-questions',
  superadminQuiz: '/superadmin/superadmin-quiz',

  superadminCertificate: '/superadmin/superadmin-certificate',
  superadminEarning: '/superadmin/superadmin-earnings',
  superadminStatements: '/superadmin/superadmin-statements',
  superadminRapports : '/superadmin/superadmin-rapports',
  superadminCompanyManagement: '/superadmin/superadmin-companymanagement',
  superadminCompanydetails: '/superadmin/superadmin-company-details',
  superadminClientList: '/superadmin/superadmin-client-list',
  superadminClientDetails: '/superadmin/superadmin-client-details',
  superadminClientAdd: '/superadmin/superadmin-client-add',
  superadminRegister: '/superadmin/superadmin-register',
  superadminCompanyAdd: '/superadmin/superadmin-company-add',
  superadminUserList: '/superadmin/superadmin-user-list',
  superadminUserDetails: '/superadmin/superadmin-user-details',
  superadminUserAdd: '/superadmin/superadmin-user-add',
  superadmin_profile: '/superadmin/superadmin-profile',
  superadminPermission: '/superadmin/superadmin-permission',
  superadminRole: '/superadmin/superadmin-role',

  // quiz:  'quiz',
  // studentsList: '/superadmin/students-list',
  // studentsGrid: '/superadmin/students-grid',
  // studentsDetails: '/superadmin/students-details',
  superadminQuizResult: '/superadmin/superadmin-quiz-results',
  superadminCourse: '/superadmin/superadmin-course',
  superadminCourseGrid: '/superadmin/superadmin-course-grid',
  superadminSession: '/superadmin/superadmin-session',
  superadminParcours: '/superadmin/superadmin-parcours',
  superadminCatalogue: '/superadmin/superadmin-catalogue',
  superadminTickets: '/superadmin/superadmin-tickets',
  superadminMessage: '/superadmin/superadmin-message',
  superadminQuizDetails: '/superadmin/superadmin-quiz-details',
  superadminSettingWithdraw: '/superadmin/settings/superadmin-setting-withdraw',
  superadminSettingNotifications: '/superadmin/settings/superadmin-setting-notifications',
  superadminPlans: '/superadmin/settings/superadmin-plans',
  superadminIntegrations: '/superadmin/settings/superadmin-integrations',
  superadminLinkedAccounts: '/superadmin/settings/superadmin-linked-accounts',
  superadminSocialProfiles: '/superadmin/settings/superadmin-social-profiles',
  superadminDeleteAccount: '/superadmin/settings/superadmin-delete-account',
  superadminChangePassword: '/superadmin/settings/superadmin-change-password',
  superadminSettings: '/superadmin/settings/superadmin-settings',
  superadminAuditLogs: '/superadmin/superadmin-audit-logs',
  superadminSondage: '/superadmin/superadmin-sondage',
  superadminGuideUtilisation: '/superadmin/manage-guide-utilisation',
  superadminVideoAccueil: '/superadmin/manage-video-acceuil',
  superadminTutorielsVideo: '/superadmin/manage-tutoriels-video',
  superadminAnnoncesMAJ: '/superadmin/manage-annonces',

  // Adminrh Routes
  adminrh: '/adminrh/',
  adminrh_dashboard: '/adminrh/adminrh-dashboard',
  adminrh_payouts: '/adminrh/adminrh-payouts',
  adminrh_tickets: '/adminrh/adminrh-tickets',
  adminrhAnnouncements: '/adminrh/adminrh-announcements',
  adminrhAssignment: '/adminrh/adminrh-assignment',
  adminrhWishlist: '/adminrh/adminrh-wishlist',
  adminrhWithdraw: '/adminrh/adminrh-withdraw',
  adminrhProfile: '/adminrh/adminrh-profile',
  adminrhQuizQuestion: '/adminrh/adminrh-quiz-questions',
  adminrhQuiz: '/adminrh/adminrh-quiz',
  adminrhQuizResult: '/adminrh/adminrh-quiz-results',
  adminrhCertificate: '/adminrh/adminrh-certificate',
  adminrhCertificateModele: '/adminrh/adminrh-certificate-modele',
  adminrhSondage: '/adminrh/adminrh-sondage',
  adminrhMesSondages: '/adminrh/adminrh-mes-sondages',
  adminrhEarning: '/adminrh/adminrh-earnings',
  adminrhRapport: '/adminrh/adminrh-rapport',
  adminrhStatements: '/adminrh/adminrh-statements',

  adminrhCompanyManagement: '/adminrh/adminrh-companymanagement',
  adminrhCompanydetails: '/adminrh/adminrh-company-details',
  adminrhClientList: '/adminrh/adminrh-client-list',
  adminrhClientDetails: '/adminrh/adminrh-client-details',
  adminrhClientAdd: '/adminrh/adminrh-client-add',
  adminrhRegister: '/adminrh/adminrh-register',
  adminrhCompanyAdd: '/adminrh/adminrh-company-add',
  adminrhUserList: '/adminrh/adminrh-user-list',
  adminrhUserGroupList: '/adminrh/adminrh-user-group-list',
  adminrhUserDetails: '/adminrh/adminrh-user-details',
  adminrhUserAdd: '/adminrh/adminrh-user-add',
  adminrh_profile: '/adminrh/adminrh-profile',
  adminrhPermission: '/adminrh/adminrh-permission',
  adminrhRole: '/adminrh/adminrh-role',
  adminrhDemande: '/adminrh/adminrh-demande',
  adminrhDemandeSession: '/adminrh/adminrh-demande-session',
  adminrhDemandeParcours: '/adminrh/adminrh-demande-parcours',
  adminrhDemandeCatalogue: '/adminrh/adminrh-demande-catalogue',
  adminrhSession: '/adminrh/adminrh-session',  // ✅ lead
  adminrhDirection: '/adminrh/adminrh-direction',
  adminrhCourse: '/adminrh/adminrh-course',
  adminrhCategorie: '/adminrh/adminrh-categorie',
  adminrhCatalogue: '/adminrh/adminrh-catalogue',
  adminrhParcours: '/adminrh/adminrh-parcours',
  adminrhCourseGrid: '/adminrh/adminrh-course-grid',
  adminrhTickets: '/adminrh/adminrh-tickets',
  adminrhMessage: '/adminrh/adminrh-message',
  adminrhQuizDetails: '/adminrh/adminrh-quiz-details',
  adminrhSettingWithdraw: '/adminrh/settings/adminrh-setting-withdraw',
  adminrhSettingNotifications: '/adminrh/settings/adminrh-setting-notifications',
  adminrhPlans: '/adminrh/settings/adminrh-plans',
  adminrhIntegrations: '/adminrh/settings/adminrh-integrations',
  adminrhLinkedAccounts: '/adminrh/settings/adminrh-linked-accounts',
  adminrhSocialProfiles: '/adminrh/settings/adminrh-social-profiles',
  adminrhDeleteAccount: '/adminrh/settings/adminrh-delete-account',
  adminrhChangePassword: '/adminrh/settings/adminrh-change-password',
  adminrhSettings: '/adminrh/settings/adminrh-settings',
  adminrhGuideUtilisation: '/adminrh/guide-utilisation',
  adminrhTutorielsVideo: '/adminrh/tutoriels-video',
  adminrhAnnoncesMAJ: '/adminrh/adminrh-announcements',

  // Pages Routes
  pages: '/pages/',
  page_notifications: '/pages/notifications',
  becomeAnExpert: '/pages/become-an-instructor',
  testimonial: '/pages/testimonial',
  aboutUs: '/pages/about-us',
  contactUs: '/pages/contact-us',
  page_pricing_plan: '/pages/pricing-plan',
  page_faq: '/pages/faq',
  page_term_condition: '/pages/term-condition',
  page_privacy_policy: '/pages/privacy-policy',
  instructorDetails: '/pages/instructor-details',
  instructorGrid: '/pages/instructor-grid',
  instructorList: '/pages/instructor-list',

  // Blog Routes
  blog: '/blog/',
  blog_details_left_sidebar: '/blog/blog-details-left-sidebar',
  blog_details_right_sidebar: '/blog/blog-details-right-sidebar',
  blog_details: '/blog/blog-details',
  blog_masonry: '/blog/blog-masonry',
  blog_grid: '/blog/blog-grid',
  blog_grid2: '/blog/blog-2-grid',
  blog_grid3: '/blog/blog-3-grid',
  blog_carousal: '/blog/blog-carousal',
  blog_left_sidebar: '/blog/blog-left-sidebar',
  blog_right_sidebar: '/blog/blog-right-sidebar',

  // Auth Routes
  auth: '/auth/',
  forgot_password: '/auth/forgot-password',
  login: '/auth/login',
  register: '/auth/register',
  setPassword: '/auth/set-password',
  otp: '/auth/otp',
  magic_verify: '/auth/magic-verify',
  activate: '/auth/activate',
  lockScreen: '/auth/lock-screen',

  under_construction: '/under-construction',
  comming_soon: '/coming-soon',
  error_404: '/error-404',
  error_500: '/error-500',

  // Home Routes
  home: '/index',
  home2: '/index-two',
  home3: '/index-three',
  home4: '/index-four',
  home5: '/index-five',
  home6: '/index-six',

  // Courses Routes
  courses: '/courses',
  courseGrid: '/courses/course-grid',
  courseList: '/courses/course-list',
  courseCategory: '/courses/course-category',
  courseCategory2: '/courses/course-category-2',
  courseCategory3: '/courses/course-category-3',
  courseResume: '/courses/course-resume',
  courseWatch: '/courses/course-watch',
  cart: '/courses/cart',
  checkout: '/courses/checkout',
  courseDetails: '/courses/course-details',
  courseDetails2: '/courses/course-details-2',
  addCourse: '/courses/add-course',
  instructorCourseAdd: '/courses/instructor-course-add',
  instructorCourseDetails: '/courses/instructor-course-details',
  instructorCourseEdit: '/courses/instructor-course-edit',
};

export default routes;
